In [4]:
# conda install numpy
import numpy as np
print(np.__version__)

1.26.3


In [6]:
# 1.1.
vector = np.arange(1, 11)
vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
# 1.2.
matrix = np.zeros((3, 3))
matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
# 1.3.
random_matrix_5x5 = np.random.randint(1, 11, size=(5, 5))
random_matrix_5x5

array([[ 1,  2,  3,  3,  6],
       [ 3,  7,  3,  5,  4],
       [ 1,  2, 10,  5,  3],
       [ 7,  8,  9,  3, 10],
       [ 7,  3,  5,  3,  7]])

In [16]:
# 1.4.
random_matrix_4x4 = np.random.random((4, 4))
random_matrix_4x4


array([[0.63963976, 0.04068851, 0.21347244, 0.4035206 ],
       [0.91163228, 0.96762404, 0.50857586, 0.83961686],
       [0.53519176, 0.45604827, 0.10464503, 0.54283143],
       [0.81135773, 0.31672127, 0.31001851, 0.2498413 ]])