In [2]:
# conda install numpy
import numpy as np
print(np.__version__)

1.26.3


In [6]:
# 1.1.
vector = np.arange(1, 11)
vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
# 1.2.
matrix = np.zeros((3, 3))
matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
# 1.3.
random_matrix_5x5 = np.random.randint(1, 11, size=(5, 5))
random_matrix_5x5

array([[ 1,  2,  3,  3,  6],
       [ 3,  7,  3,  5,  4],
       [ 1,  2, 10,  5,  3],
       [ 7,  8,  9,  3, 10],
       [ 7,  3,  5,  3,  7]])

In [16]:
# 1.4.
random_matrix_4x4 = np.random.random((4, 4))
random_matrix_4x4


array([[0.63963976, 0.04068851, 0.21347244, 0.4035206 ],
       [0.91163228, 0.96762404, 0.50857586, 0.83961686],
       [0.53519176, 0.45604827, 0.10464503, 0.54283143],
       [0.81135773, 0.31672127, 0.31001851, 0.2498413 ]])

In [17]:
# 1.5.
array_1 = np.random.randint(1, 11, size=5)
array_2 = np.random.randint(1, 11, size=5)

addition = array_1 + array_2
subtraction = array_1 - array_2
multiplication = array_1 * array_2

array_1, array_2, addition, subtraction, multiplication

(array([8, 5, 8, 2, 6]),
 array([4, 5, 8, 4, 1]),
 array([12, 10, 16,  6,  7]),
 array([ 4,  0,  0, -2,  5]),
 array([32, 25, 64,  8,  6]))

In [19]:
# 1.6.
vector_1 = np.random.randint(1, 101, size=7)
vector_2 = np.random.randint(1, 101, size=7)

scalar_result = np.dot(vector_1, vector_2)

vector_1, vector_2, scalar_result


(array([ 44,  12,  55, 100,  78,  10,  76]),
 array([43, 28, 87,  1, 20,  7, 42]),
 11935)

In [20]:
# 1.7.
matrix_1 = np.random.randint(1, 11, size=(2, 2))
matrix_2 = np.random.randint(1, 11, size=(2, 3))

multiplication_result = np.dot(matrix_1, matrix_2)

matrix_1, matrix_2, multiplication_result

(array([[ 9,  2],
        [ 1, 10]]),
 array([[1, 6, 8],
        [4, 5, 1]]),
 array([[17, 64, 74],
        [41, 56, 18]]))

In [21]:
# 1.8.
matrix = np.random.randint(1, 101, size=(3, 3))

inv_matrix = np.linalg.inv(matrix)

matrix, inv_matrix

(array([[53, 46, 89],
        [16, 53, 39],
        [45, 16, 76]]),
 array([[ 0.21647059, -0.13176471, -0.18588235],
        [ 0.03427663,  0.00146264, -0.0408903 ],
        [-0.13538951,  0.07771065,  0.1318283 ]]))

In [6]:
# 1.9. 
matrix = np.random.random((4, 4))

transposed_matrix = matrix.T

matrix, transposed_matrix

(array([[0.78299128, 0.31208012, 0.30456176, 0.38726614],
        [0.96012403, 0.05872908, 0.6494785 , 0.79786937],
        [0.82753173, 0.28861259, 0.14963087, 0.93625989],
        [0.63215072, 0.67196816, 0.18369882, 0.67017916]]),
 array([[0.78299128, 0.96012403, 0.82753173, 0.63215072],
        [0.31208012, 0.05872908, 0.28861259, 0.67196816],
        [0.30456176, 0.6494785 , 0.14963087, 0.18369882],
        [0.38726614, 0.79786937, 0.93625989, 0.67017916]]))

In [5]:
# 1.10.
vector = np.random.randint(1, 11, size=4)
matrix = np.random.randint(1, 11, size=(3, 4))

result = np.dot(matrix, vector)

matrix, vector, result

(array([[ 7,  4,  4,  1],
        [ 1, 10,  4, 10],
        [ 4,  2,  9,  5]]),
 array([ 5, 10,  8, 10]),
 array([117, 237, 162]))

In [6]:
# 1.11.
matrix = np.random.random(size=(2, 3))
vector = np.random.random(size=3)

result = np.dot(matrix, vector)

matrix, vector, result

(array([[0.14481504, 0.38603821, 0.7166688 ],
        [0.78362799, 0.43217994, 0.31418998]]),
 array([0.45273336, 0.53595558, 0.00403784]),
 array([0.27535573, 0.58767243]))

In [8]:
# 1.12.
matrix_1 = np.random.randint(1, 11, size=(2, 2))
matrix_2 = np.random.randint(1, 11, size=(2, 2))

matrix_multiplication = np.multiply(matrix_1, matrix_2)

matrix_1, matrix_2, matrix_multiplication

(array([[ 2,  7],
        [ 5, 10]]),
 array([[9, 1],
        [6, 6]]),
 array([[18,  7],
        [30, 60]]))

In [9]:
# 1.13.
matrix_1 = np.random.randint(1, 11, size=(2, 2))
matrix_2 = np.random.randint(1, 11, size=(2, 2))

multiplication = np.dot(matrix_1, matrix_2)

matrix_1, matrix_2, multiplication

(array([[8, 5],
        [1, 8]]),
 array([[3, 1],
        [1, 5]]),
 array([[29, 33],
        [11, 41]]))